version: '3.8'

services:

  weathermicroservice:
    container_name: weathermicroservice
    build: .
    ports:
      - "5000:80"
      - "5001:443"
      - "1234:1234"
    depends_on:
      - prometheus
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./Data:/app/Data
    restart: always
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:80/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:9090" ]
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:3000" ]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - prometheus

volumes:
  dbdata:
  grafana-storage:
